### ISSUE TITLE
!Play -p Playlist only added first song of playlist to the queue

### ISSUE THREAD

**Issue by Techtony96** [Techtony96/Discord.java#25]

**Comment by Techtony96** [comment]
In testing this worked just fine. Need reproducible steps. @Jesseee can you take a look at this?

**Comment by LegitJesseee** [comment]
Can't reproduce

**Comment by Techtony96** [comment]
Was able to reproduce this, but it added 5 songs instead of just one. 
Proof:
![image](https://cloud.githubusercontent.com/assets/1782682/26022456/fabaf6ba-3773-11e7-9f74-7c0c13441682.png)

**Comment by Techtony96** [comment]
Figured out what the problem was, it takes a long time for LOTS of songs to be added. 30-45 seconds so I added a message explaining that.

**Comment by Techtony96** [comment]
0da45201a4073a6d29e528455b0dd7d50b1fa6ee
